import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Header } from "../components/header";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to a calculator</h1>

        <Header />

        <div className={`${styles.grid} ${styles.flex_column}`}>
          <Image
            src="/shmoney.png"
            alt="make that shmoney"
            width="331"
            height="679"
          />
          <p>Save that gp</p>
        </div>
      </main>
    </div>
  );
};

export default Home;
